name: Neural Feedback MCP Server

on:
  push:
    branches:
      - main
    paths:
      - 'config/mcp/providers/src/neural-feedback/**'
      - 'docker/neural-feedback/**'
      - 'k8s/base/neural-feedback/**'
      - '.github/workflows/neural-feedback.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aeonnovafuturelabs/neural-feedback

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=ref,event=tag

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/neural-feedback/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Kubernetes manifests
        run: |
          cd k8s/base/neural-feedback
          kustomize edit set image anfl/neural-feedback=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.meta.outputs.digest }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kustomization.yaml
          git commit -m "Update neural-feedback image to ${{ steps.meta.outputs.digest }}"
          git push